name: Generate Movie Release Daily

on:
  schedule:
    - cron: '0 45 09 * * ?' # Runs everyday @ 10:15 am
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: twitter-quotes-bot
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python tweepy-test.py
        